spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:database
  web:
    locale: ko_KR
    locale-resolver: fixed
security:
  secret-key: "Yn2kjibddFAWtnPJ2AFlL8WXmohJMCvigQggaEypa5E="
  token-expiration-second: 604800
